ARG ST2_VERSION
FROM stackstorm/st2actionrunner:${ST2_VERSION}

RUN wget https://github.com/muyouming/sapnwrfcsdk/raw/master/nwrfc750P_5-70002752.zip
RUN apt install unzip
RUN unzip nwrfc750P_5-70002752.zip
RUN mkdir -p /usr/local/sap
RUN mv nwrfc750P_5-70002752/nwrfcsdk/ /usr/local/sap/
RUN echo "/usr/local/sap/nwrfcsdk/lib" >>/etc/ld.so.conf.d/nwrfcsdk.conf

RUN ldconfig
